DotNet/TimesheetManagementSystem/Models/ErrorViewModel.cs
namespace TimesheetManagementSystem.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

DotNet/TimesheetManagementSystem/Controllers/HomeController.cs
using System.Diagnostics;
using BOL;
using DAL;
using Microsoft.AspNetCore.Mvc;
using TimesheetManagementSystem.Models;

namespace TimesheetManagementSystem.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index(){
        return View();
    }

    public IActionResult Login(string name, string password)
    {
        List<Employee> es = DBEmployee.LoginData(name, password);
        foreach (Employee e in es)
        {
            if(e.name==name && e.password==password){
             return Redirect("Display");
            }
        }
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

DotNet/TimesheetManagementSystem/Controllers/TimesheetController.cs
using System.Diagnostics;
using BLL;
using BOL;
using DAL;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Asn1.Cms;
using TimesheetManagementSystem.Models;

namespace TimesheetManagementSystem.Controllers;

public class TimesheetController : Controller
{
    private readonly ILogger<TimesheetController> _logger;

    public TimesheetController(ILogger<TimesheetController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Display()
    {
        BLLManager bobj = new BLLManager();
        List<Timesheet> allData = bobj.GetAll();
        ViewData["allTimesheets"] = allData;
        return View();
    }

    public IActionResult Insert(int id, string date, string work_description, int hours, string status)
    {
        Timesheet ts = new Timesheet(id, date, work_description, hours, status);
        DBTimesheet.InsertData(ts);
        return View();
    }
    

    public IActionResult Details(int id)
    {
        Timesheet ts = DBTimesheet.GetById(id);
        ViewData["data"] = ts;
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

DotNet/TimesheetManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotNet/TimesheetManagementSystem/Views/Home/Login.cshtml
<form action="/Timesheet/Display">
    Enter Name: <input type="text" name="name"> <br>
    Enter Password <input type="text" name="email"> <br>
    <input type="submit" value="login">
</form>

DotNet/TimesheetManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimesheetManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TimesheetManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TimesheetManagementSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"></a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Timesheet" asp-action="Display">Display</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Timesheet" asp-action="Insert">Insert</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TimesheetManagementSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DotNet/TimesheetManagementSystem/Views/Timesheet/Details.cshtml
 @using BOL;

@{
    ViewData["Title"] = "Timesheeet List";
}

@{
        Timesheet ts = (Timesheet)ViewData["data"];


        <table class="table">
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Work Description</th>
                <th>Hours</th>
                <th>Status</th>
                
            </tr>

            @* @foreach (Timesheet t in ts){ *@

                <tr>
                    <td>@ts.id</td>
                    <td>@ts.date</td>
                    <td>@ts.work_description</td>
                    <td>@ts.hours</td>
                    <td>@ts.status</td>
                    @* <td> <a href="/details/@t.id"> details </a></td> *@
                </tr>

            @* } *@

        </table>
    }

DotNet/TimesheetManagementSystem/Views/Timesheet/Display.cshtml
@using BOL;

@{
    ViewData["Title"] = "Timesheeet List";
}
@{
        List<Timesheet> allData = (List<Timesheet>)ViewData["allTimesheets"];
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Work Description</th>
                <th>Hours</th>
                <th>Status</th>
                
            </tr>

            @foreach (Timesheet t in allData){

                <tr>
                    <td>@t.id</td>
                    <td>@t.date</td>
                    <td>@t.work_description</td>
                    <td>@t.hours</td>
                    <td>@t.status</td>
                    <td> <a href="/Timesheet/details/@t.id"> details </a></td>
                </tr>
            }
        </table>
    }

DotNet/TimesheetManagementSystem/Views/Timesheet/Insert.cshtml
@{
    ViewData["Title"] = "Insert TimeSheet Data";
}


<form>
    Enter Id: <input type="number" name="id"> <br>
    Enter Date: <input type="text" name="date" placeholder="DD/MM/YYYY"> <br>
    Enter Work Desc: <input type="text" name="work_description"> <br>
    Enter hours: <input type="number" name="hours"> <br>
    Enter status: <input type="text" name="status"> <br>
    <input type="submit" value="Insert">
</form>